# @package _global_

defaults:
  - train
  - override /task: libero10_idm_proprio_joint_2cam224_1e-4
  - _self_

self_forcing:
  video_chunk_size: 3
  video_rollout_steps: 4
  context_noise: 0.0

wandb:
  name: train_idm_self_forcing_proprio_joint
